apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  DB_PASSWORD: "1234"
  JWT_SECRET: "change-me-to-a-long-random-secret-at-least-32-bytes"
  ENCRYPTION_KEY: "change-me-to-a-random-encryption-secret"
  GEMINI_API_KEY: "no-key"
