spring:
  config:
    activate:
      on-profile: dev
  flyway:
    locations: classpath:db/migration,classpath:db/migration/dev

app:
  scheduling:
    week-summary:
      cron: "0 */5 * * * *"
    month-summary:
      cron: "0 */10 * * * *"
    year-summary:
      cron: "0 */30 * * * *"