server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/expense_tracker_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/migration/dev
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:no-key}
        chat:
          model: gemini-3.6-flash
jwt:
#  treba da se smeni so environment variable, so ne se cuva vo git
  secret: ${JWT_SECRET:dev-fallback-secret-at-least-32-bytes-long-for-local-testing}
app:
  security:
    # isto, ova e za da ne se chuva raw api key
    encryption-key: ${ENCRYPTION_KEY:dev-fallback-encryption-secret-change-in-prod}
  scheduling:
    zone: Europe/Skopje
    week-summary:
      cron: "0 0 3 * * MON"
    month-summary:
      cron: "0 0 3 1 * *"
    year-summary:
      cron: "0 0 3 1 1 *"